config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'websites#index'

  get 'admin/configurable' => 'admin/configurables#show', as: 'admin_configurables'

  resources :websites do
    post 'activate',   :on => :member
    post 'deactivate', :on => :member
  end

  resources :recipients

  get 'background_jobs' => 'background_jobs#show', as: 'background_jobs'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :website

  default_scope -> { order(:created_at => :desc) }

  def success?
    # 2x and 3x are considered being successfull
    %(2 3).include? response_code.to_s[0]
  end

  def failure?
    not success?
  end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, uniqueness: true, email: true, if: -> { email.present? }

  default_scope -> { order(:created_at => :desc) }
end

app/models/website.rb
class Website < ActiveRecord::Base
  STATUSES = { failing: 'failing', success: 'success', pending: 'pending' }
  CHECKS_QUEUE = "website_checks"

  validates :check_interval, :url, presence: true
  # only validate url format if url is present (avoid unnecesarry validation errors)
  validates :url, url: true, uniqueness: true, if: -> { url.present? }
  # check_interval must be greater than "critical_check_interval" value!
  # uses lambda to avoid "production" mode class caching missbehivour
  validates :check_interval, numericality: { greater_than: -> (website) { Configurable.critical_check_interval } }, if: -> { check_interval.present? }

  default_scope -> { order(:created_at => :desc) }

  has_many :checks, :dependent => :destroy

  #####
  # Creates a self-recursive background job that will launch in #check_interval seconds after record creation and will
  # re-run itself upon completion
  #####
  after_create :schedule!

  #####
  # Remove running and scheduled jobs
  #####
  before_destroy :deactivate!

  # Overwrites default #check_interval
  def check_interval
    failing?? Configurable.critical_check_interval : read_attribute(:check_interval)
  end

  def status
    if failing?
      STATUSES[:failing]
    else
      if checks.any?
        checks.first.success?? STATUSES[:success] : STATUSES[:pending]
      else
        STATUSES[:pending]
      end
    end
  end

  def requires_failure_notification?
    _critical_failures_count = Configurable.critical_failures_count

    if recent_failures_count > _critical_failures_count
      # tell if a number is in arithmetic seq
      ( (recent_failures_count - _critical_failures_count) % Configurable.repeat_notification_failures_count ).zero?
    else
      recent_failures_count == _critical_failures_count
    end
  end

  def uri
    @_uri ||= URI.parse(url).tap { |website_url| website_url.path = "/" if website_url.path.empty? }
  end

  def https?
    uri.scheme == 'https'
  end

  def failing?
    recent_failures_count >= Configurable.critical_failures_count
  end

  def schedule!
    # CsvImportJob.set(wait_until: Date.tomorrow.noon).perform_later('/tmp/my_file.csv')
    WebsiteCheck.set(wait: check_interval.seconds).perform_later(id) # perform_in check_interval.seconds, id
  end

  def recover!
    update_attribute :recent_failures_count, 0

    recovery_notification!
  end

  def failing!
    increment! :recent_failures_count

    failure_notification! if requires_failure_notification?
  end

  def scheduled?
    schedule = Sidekiq::ScheduledSet.new

    schedule.find { |job| job.args.first['arguments'].include?(id) and job.queue == CHECKS_QUEUE }.present?
  end

  def running?
    queue = Sidekiq::Queue.new(CHECKS_QUEUE)

    queue.find { |job| job.args.first.arguments.include?(id) }.present?
  end

  def activate!
    update_attribute :active, true

    schedule! unless scheduled? or running?
  end

  def deactivate!
    update_attribute :active, false

    stop_running_jobs!
    remove_scheduled_jobs!
  end

  private

  def failure_notification!
    if recent_failures_count > Configurable.critical_failures_count
      NotificationMailer.repetitive_failure(self).deliver_later
    else
      NotificationMailer.failure(self).deliver_later
    end
  end

  def recovery_notification!
    NotificationMailer.recovery(self).deliver_later
  end

  def stop_running_jobs!
    Sidekiq.redis do |redis|
      queue_key = "queue:#{CHECKS_QUEUE}"
      jobs = redis.lrange(queue_key, 0, -1)

      jobs.each do |job|
        redis.lrem(queue_key, 0, job) if JSON.load(job)['args'].first['arguments'].include?(id)
      end
    end
  end

  def remove_scheduled_jobs!
    schedule = Sidekiq::ScheduledSet.new
    jobs = schedule.select { |job| job.args.first['arguments'].include?(id) }

    jobs.each(&:delete)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  clear_helpers
end

app/controllers/background_jobs_controller.rb
class BackgroundJobsController < ApplicationController
  def show
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_filter :find_recipient!, only: [ :edit, :destroy, :update ]

  def index
    @recipients = Recipient.all
    @recipient  = Recipient.new
  end

  def create
    @recipient = Recipient.create(recipient_params)

    if @recipient.persisted?
      render json: { recipient: render_to_string(partial: 'recipient', locals: { recipient: @recipient }) }, status: 202
    else
      render json: { errors: @recipient.errors }, status: 422
    end
  end

  def update
    if @recipient.update(recipient_params)
      redirect_to recipients_path, notice: I18n.t('flash.recipients.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @recipient.destroy

    render nothing: true, status: 200
  end

  private

  def find_recipient!
    @recipient = Recipient.find(params[:id])
  end

  def recipient_params
    params.require(:recipient).permit(:name, :email)
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_filter :find_website!, only: [ :edit, :destroy, :update, :show, :activate, :deactivate ]

  def index
    @websites = Website.all
    @website  = Website.new
  end

  def show
    @checks = @website.checks
  end

  def create
    @website = Website.create(website_params)

    if @website.persisted?
      render json: { website: render_to_string(partial: 'website', locals: { website: @website }) }, status: 202
    else
      render json: { errors: @website.errors }, status: 422
    end
  end

  def update
    if @website.update(website_params)
      redirect_to websites_path, notice: I18n.t('flash.websites.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @website.destroy

    render nothing: true, status: 200
  end

  def activate
    @website.activate!

    render nothing: true, status: 200
  end

  def deactivate
    @website.deactivate!

    render nothing: true, status: 200
  end

  private

  def find_website!
    @website = Website.find(params[:id])
  end

  def website_params
    params.require(:website).permit(:url, :check_interval)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_link(text, path, options)
    active = options.delete(:active)

    content_tag :li, link_to(text, path, options), class: active ? 'active' : ''
  end

  def page_header(text = t('.header'))
    content_tag :div, content_tag(:h1, text), class: 'page-header'
  end

  def icon(classes, tooltip = nil)
    class_names = ['glyphicon'] + classes.split(' ')

    content_tag :i, nil, class: class_names.join(' '), title: tooltip
  end

  def icon_label(icon_class, text)
    "#{icon(icon_class)} #{text}".html_safe
  end

  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
        concat content_tag(:button, t('common.x'), class: 'close', data: { dismiss: 'alert' })
        concat message
      end)
    end

    nil
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def icon_status(status)
    case status
    when 'pending' then icon('glyphicon-off text-muted')
    when 'success' then icon('glyphicon-circle-arrow-up text-success')
    when 'failing' then icon('glyphicon-circle-arrow-down text-danger')
    end
  end
end

app/views/admin/configurables/show.html.erb
<%= page_header %>

<div class='container'>
  <%= form_tag(admin_configurable_path, :method => :put, class: 'form form-horizontal') do -%>
    <%- @keys.each do |key| -%>
      <%- options = Configurable.defaults[key] -%>
      <div class="form-group">
        <%= label_tag key, options[:name], class: 'col-sm-2 control-label' %>

        <%- if options[:type] == 'boolean' %>
          <%= hidden_field_tag key, "0" %>
          <div class='col-sm-10'> <%= check_box_tag key, "1", Configurable.send(key), class: 'form-control' %> </div>
        <%- elsif options[:type] == 'password' -%>
          <div class='col-sm-10'> <%= password_field_tag key, Configurable.send(key), class: 'form-control' %> </div>
        <%- elsif options[:type] == 'text' -%>
          <div class='col-sm-10'> <%= text_area_tag key, Configurable.send(key), class: 'form-control' %> </div>
        <%- elsif options[:type] == 'list' -%>
          <div class='col-sm-10'> <%= text_area_tag key, Configurable.serialized_value(key), class: 'form-control' -%> </div>
        <%- else -%>
          <div class='col-sm-10'> <%= text_field_tag key, Configurable.send(key), class: 'form-control' %> </div>
        <%- end -%>
      </div>
    <%- end -%>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= submit_tag 'Save', class: 'btn btn-primary', data: { disable_with: t('common.please_wait') } %>
      </div>
    </div>
  <%- end -%>
</div>

app/views/application/_header.erb
<nav class='navbar navbar-default' id='header'>
  <div class='container-fluid'>

    <div class="navbar-header">
      <%= content_tag :button, class: 'navbar-toggle collapsed', data: { toggle: 'collapse', target: '#navbar-controls' } do %>
        <span class='sr-only'> <%= t '.toggle_navigation' %> </span>

        <% 3.times do %>
          <span class='icon-bar'></span>
        <% end %>
      <% end %>

      <%= link_to t('.brand'), root_path, class: 'navbar-brand', data: { no_turbolink: true } %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-controls">
      <ul class="nav navbar-nav">
        <%= navbar_link t('.websites'), websites_path, active: %w(websites).include?(controller_name) %>
        <%= navbar_link t('.recipients'), recipients_path, active: %w(recipients).include?(controller_name) %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= navbar_link t('.configurations'), admin_configurables_path, active: %w(configurables).include?(controller_name) %>
        <%= navbar_link t('.sidekiq'), background_jobs_path, active: %w(background_jobs).include?(controller_name), data: { no_turbolink: true } %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/background_jobs/show.html.erb
<iframe src='<%= sidekiq_web_path %>' frameborder="0" style="position:absolute" height="100%" width="100%" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kama</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='<%= controller_name.dasherize %>' data-action='<%= action_name.dasherize %>'>

<%= render 'header' %>

<div class='container'> <%= flash_messages %> </div>

<div class='container-fluid'>
  <%= yield %>
</div>

</body>
</html>

app/views/recipients/_form.erb
<%= simple_form_for @recipient, remote: !@recipient.persisted?, html: { id: 'recipient' } do |form| %>
  <%= form.input :name %>
  <%= form.input :email %>

  <%= form.submit t('common.submit'), class: 'btn btn-primary', data: { disable_with: t('common.please_wait') } %>
<% end %>
<hr>

app/views/recipients/_recipient.erb
<tr>
  <td> <%= recipient.name %> </td>
  <td> <%= recipient.email %> </td>

  <td class='options'>
    <%= link_to icon('glyphicon-pencil', t('common.edit')), edit_recipient_path(recipient) %>
    <%= link_to icon('glyphicon-remove text-danger', t('common.destroy')), recipient_path(recipient), method: 'delete', class: 'destroy-recipient',
      data: { remote: true, confirm: t('common.are_you_sure?') } %>
  </td>
</tr>

app/views/recipients/edit.html.erb
<%= page_header t('.header', recipient: @recipient.name) %>

<div class='container'>
  <%= render 'form' %>
</div>

app/views/recipients/index.html.erb
<%= page_header %>

<%= link_to icon_label('glyphicon-plus', t('.new')), nil, id: 'new-recipient-form-toggler', class: 'btn btn-primary' %>

<hr>
<div id='new-recipient-form-container'>
  <%= render 'form' %>
</div>

<table class='table table-condensed' id='recipients'>
  <colgroup>
    <col span='1' class='col-md-5 col-lg-5'/>
    <col span='1' class='col-md-5 col-lg-5'/>
    <col span='1' class='col-md-2 col-lg-2'/>
  </colgroup>

  <thead>
    <th> <%= t '.name'          %> </th>
    <th> <%= t '.email'         %> </th>
    <th> <%= t 'common.options' %> </th>
  </thead>

  <tbody>
    <%= render @recipients %>
  </tbody>
</table>

app/views/websites/_form.erb
<%= simple_form_for @website, remote: !@website.persisted?, html: { id: 'website' } do |form| %>
  <%= form.input :url %>
  <%= form.input :check_interval, input_html: { value: form.object.check_interval || Configurable.default_check_interval } %>

  <%= form.submit t('common.submit'), class: 'btn btn-primary', data: { disable_with: t('common.please_wait') } %>
<% end %>
<hr>

app/views/websites/_website.erb
<tr class='<%= "inactive" unless website.active? %>'>
  <td> <%= link_to website.url, website_path(website) %> </td>
  <td> <strong class='website-status'> <%= t(".statuses.#{website.status}") %> <span> <%= icon_status(website.status) %> </span> </strong> </td>
  <td> <%= website.check_interval %> </td>

  <td class='options'>
    <%= link_to icon('glyphicon-pencil', t('common.edit')), edit_website_path(website) %>
    <%= link_to icon('glyphicon-remove text-danger', t('common.destroy')), website_path(website), method: 'delete', class: 'destroy-website',
      data: { remote: true, confirm: t('common.are_you_sure?') } %>
    <%= link_to icon('glyphicon-pause text-danger', t('.pause')), deactivate_website_path(website), method: 'post', class: 'deactivate-website',
      data: { remote: true, confirm: t('common.are_you_sure?') } %>
    <%= link_to icon('glyphicon-play text-success', t('.resume')), activate_website_path(website), method: 'post', class: 'activate-website', data: { remote: true } %>
  </td>
</tr>

app/views/websites/edit.html.erb
<%= page_header t('.header', website: @website.url) %>

<div class='container'>
  <%= render 'form' %>
</div>

app/views/websites/index.html.erb
<%= page_header %>

<%= link_to icon_label('glyphicon-plus', t('.new')), nil, id: 'new-website-form-toggler', class: 'btn btn-primary' %>

<hr>
<div id='new-website-form-container'>
  <%= render 'form' %>
</div>

<table class='table table-condensed' id='websites'>
  <colgroup>
    <col span='1' class='col-md-5 col-lg-5'/>
    <col span='1' class='col-md-3 col-lg-3'/>
    <col span='1' class='col-md-2 col-lg-2'/>
    <col span='1' class='col-md-2 col-lg-2'/>
  </colgroup>

  <thead>
    <th> <%= t '.url'            %> </th>
    <th> <%= t '.status'         %> </th>
    <th> <%= t '.check_interval' %> </th>
    <th> <%= t 'common.options'  %> </th>
  </thead>

  <tbody>
    <%= render @websites %>
  </tbody>
</table>

app/views/websites/show.html.erb
<%= page_header t('.header', website: @website.url) %>

<table id='website-checks' class='table table-condensed'>
  <col span='1' class='col-md-10 col-lg-10'/>
  <col span='1' class='col-md-2 col-lg-2'/>

  <thead>
    <th> <%= t '.created_at' %> </th>
    <th> <%= t '.response_code' %> </th>
  </thead>

  <tbody>
    <% @website.checks.each do |check| %>
      <tr>
        <td> <%= l check.created_at, :format => :website_check %> </td>
        <td> <%= check.response_code %> </td>
      </tr>
    <% end %>
  </tbody>
</table>